name: CI

on:
  push:
  schedule:
    # Times are in UTC, this job is run daily @ 10HRS = 5AM EST
    - cron: "0 10 * * *"

  workflow_dispatch:

jobs:
  updateall:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: strong crypto
        shell: pwsh
        run: Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
      - name: run update_all
        shell: pwsh
        run: |
          Install-PackageProvider -Confirm:$false -Force -MinimumVersion 2.8.5.201 -Name NuGet
          Install-Module au -Confirm:$false -Force
          .\updateall_all.ps1
