name: CI

on:
  push:
  schedule:
    # Times are in UTC, this job is run daily @ 10HRS = 5AM EST
    - cron: "0 10 * * *"

  workflow_dispatch:

jobs:
  updateall:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: run update_all
        shell: pwsh
        run: |
          Install-Module au -Confirm:$false -Force
          .\update_all.ps1
          if ( ! ( Select-String -Path .\Update-AUPackages.md -Pattern "0 updated," ) ) {
            $paramsSendMailmessage = @{
              SmtpServer = "filer"
              From       = "taskscheduler@home.mustakim.com"
              To         = "alim@forwardcomputers.com"
              Subject    = "From GITHUB"
              Body       = "Chocolatey local packages updated"
              }
            Send-MailMessage @paramsSendMailmessage
          }
